language: python
sudo: false
python:
    - "2.7"
    - "3.3"
    - "3.4"
    - "3.5"
    - "3.6"
install:
    - "pip install -r requirements-tests.txt"
    - "python setup.py develop"
    - "pip install pytest_pyramid[tests] coveralls wheel"
script:
    - "py.test --pc tests/pyramid.test.ini --cov pytest_pyramid tests/ -p no:pytest_pyramid"
    - "pylama"
after_success:
    - coveralls

deploy:
    provider: pypi
    user: fizyk
    password:
        secure: AeTVshEncgd/rpqmTNeRYhTOgI4Pgw7h0lMMoqx+6xvAcpJKBi6TRqTSJ5J4zncVbMIXnDhmJl+Ftz4eFwNxkgR2D8IMUZZ2XlzU2FMvDPVQc+xNxJ6r9+xJfv6ROLWFSYiEeE+ELHb+WjcvRk9wBbiUr2TYzlI2nZipuXd9Hs0=
    on:
        tags: true
        repo: fizyk/pytest_pyramid
    distributions: "sdist bdist_wheel"
